channels:
  - defaults
dependencies:
  - python==3.7.9
  - jsonschema==3.2.0
  - pandas==1.1.1
  - requests==2.24.0
  - pip==20.2.3
  - pytest==6.0.1
  - gunicorn==20.0.4
  - xlrd==1.2.0
  - pip:
      - orjson==3.3.1
      - lxml==4.4.2
      - python-arango==6.0.0
      - tqdm==4.50.0
